// Seed data: named venues from venue-outreach-DB.md + Crete brief.
//
// CONTACT INTEGRITY RULE (per spec line 14): NEVER fabricate contact info.
// Every email/phone/instagram here was sourced from the venue's own public
// website or verified public Instagram profile. Sources noted inline.
// If a field is blank, the data was not publicly verifiable at build time.

import type { Venue } from './types'

const now = '2026-05-16T00:00:00.000Z'

const v = (id: string, partial: Omit<Venue, 'id' | 'created_at' | 'updated_at'>): Venue => ({
  id,
  created_at: now,
  updated_at: now,
  ...partial,
})

export const SEED_VENUES: Venue[] = [
  v('berghain-berlin', {
    name: 'Berghain',
    category: 'Nightclub',
    city: 'Berlin',
    district: 'Friedrichshain',
    website: 'https://www.berghain.berlin/en/',
    email: 'support@berghain.de', // verified on berghain.berlin/en/contact
    has_djs: true,
    has_events: true,
    has_audio: true,
    outdoor: false,
    luxury_score: 3,
    tourist_area: true,
    music_type: 'Techno, house',
    notes: 'Primary Berlin techno lead restored to seed pack.',
    status: 'researching',
    tags: ['NIGHTCLUB', 'TECHNO', 'EDM', 'LOCAL', 'TOURIST'],
    source: 'official website',
  }),
  v('tresor-berlin', {
    name: 'Tresor Berlin',
    category: 'Nightclub',
    city: 'Berlin',
    district: 'Mitte',
    website: 'https://tresorberlin.com/',
    has_djs: true,
    has_events: true,
    has_audio: true,
    outdoor: false,
    luxury_score: 3,
    tourist_area: true,
    music_type: 'Techno, electronic',
    notes: 'Legendary Berlin club and label with active event calendar on official site.',
    status: 'researching',
    tags: ['NIGHTCLUB', 'TECHNO', 'EDM', 'LOCAL'],
    source: 'official website',
  }),
  v('kater-blau', {
    name: 'Kater Blau',
    category: 'Nightclub',
    city: 'Berlin',
    district: 'Friedrichshain',
    website: 'https://www.katerclub.de/',
    has_djs: true,
    has_events: true,
    has_audio: true,
    outdoor: true,
    luxury_score: 3,
    tourist_area: true,
    music_type: 'Electronic, house',
    notes: 'Official site confirms club programming and resident-led nights.',
    status: 'researching',
    tags: ['NIGHTCLUB', 'HOUSE', 'OPEN_AIR', 'LOCAL', 'TOURIST'],
    source: 'official website',
  }),
  v('rex-club-paris', {
    name: 'Rex Club',
    category: 'Nightclub',
    city: 'Paris',
    district: '2nd arrondissement',
    website: 'https://rexclub.com/',
    has_djs: true,
    has_events: true,
    has_audio: true,
    outdoor: false,
    luxury_score: 3,
    tourist_area: true,
    music_type: 'Techno, electronic',
    notes: 'Restored Paris flagship club lead from official venue site.',
    status: 'researching',
    tags: ['NIGHTCLUB', 'TECHNO', 'LOCAL', 'TOURIST'],
    source: 'official website',
  }),
  v('la-machine-paris', {
    name: 'La Machine du Moulin Rouge',
    category: 'Nightclub',
    city: 'Paris',
    district: '18th arrondissement',
    website: 'https://www.lamachinedumoulinrouge.com/',
    email: 'contact@lamachinedumoulinrouge.com', // verified on official infos-contact page
    has_djs: true,
    has_events: true,
    has_audio: true,
    outdoor: false,
    luxury_score: 3,
    tourist_area: true,
    music_type: 'Club nights, concerts, electronic',
    notes: 'Official infos-contact page lists venue contact and operating details.',
    status: 'researching',
    tags: ['NIGHTCLUB', 'EVENT_SPACE', 'TECHNO', 'LIVE_MUSIC', 'TOURIST'],
    source: 'official website',
  }),
  v('pachamama-paris', {
    name: 'Pachamama Paris',
    category: 'Nightclub',
    city: 'Paris',
    district: '12th arrondissement',
    website: 'https://www.pachamama-paris.com/',
    email: 'accueil@pachamama-paris.com', // verified on official infos pratiques page
    phone: '01.55.78.10.00', // verified on official infos pratiques page
    has_djs: true,
    has_events: true,
    has_audio: true,
    outdoor: false,
    luxury_score: 4,
    tourist_area: true,
    music_type: 'Dinner club, Latin, open format',
    notes: 'Official practical info page lists main reception email and phone.',
    status: 'researching',
    tags: ['NIGHTCLUB', 'RESTAURANT', 'HIGH_END', 'TOURIST'],
    source: 'official website',
  }),
  v('zero-gravity-dubai', {
    name: 'Zero Gravity',
    category: 'Beach Club',
    city: 'Dubai',
    district: 'Dubai Marina',
    website: 'https://www.0-gravity.ae/',
    email: 'info@0-gravity.ae', // verified on homepage
    phone: '+971 4 399 0009', // verified on homepage
    has_djs: true,
    has_events: true,
    has_audio: true,
    outdoor: true,
    luxury_score: 4,
    tourist_area: true,
    music_type: 'Beach club, electronic, open format',
    notes: 'Official homepage exposes direct contact details and venue sections.',
    status: 'researching',
    tags: ['BEACH_CLUB', 'LUXURY', 'OPEN_AIR', 'TOURIST', 'HOUSE'],
    source: 'official website',
  }),
  v('barasti-dubai', {
    name: 'Barasti Beach Club',
    category: 'Beach Club',
    city: 'Dubai',
    district: 'Dubai Marina',
    website: 'https://www.barastibeach.com/',
    has_djs: true,
    has_events: true,
    has_audio: true,
    outdoor: true,
    luxury_score: 3,
    tourist_area: true,
    music_type: 'Beach bar, live events, open format',
    notes: 'Official site positions Barasti as a major Dubai beach nightlife venue.',
    status: 'researching',
    tags: ['BEACH_CLUB', 'TOURIST', 'OPEN_AIR', 'COCKTAIL'],
    source: 'official website',
  }),
  v('soho-garden-palm', {
    name: 'Soho Garden Palm',
    category: 'Beach Club',
    city: 'Dubai',
    district: 'Palm Jumeirah',
    website: 'https://www.sohogardenpalm.com/',
    has_djs: true,
    has_events: true,
    has_audio: true,
    outdoor: true,
    luxury_score: 4,
    tourist_area: true,
    music_type: 'Beach club, house, electronic',
    notes: 'Official site confirms active Dubai nightlife and beach programming.',
    status: 'researching',
    tags: ['BEACH_CLUB', 'LUXURY', 'HOUSE', 'OPEN_AIR', 'TOURIST'],
    source: 'official website',
  }),
  v('paradiso-amsterdam', {
    name: 'Paradiso',
    category: 'Live Music Venue',
    city: 'Amsterdam',
    district: 'Centrum',
    website: 'https://www.paradiso.nl/en/',
    has_djs: true,
    has_events: true,
    has_audio: true,
    outdoor: false,
    luxury_score: 3,
    tourist_area: true,
    music_type: 'Live music, club nights, electronic',
    notes: 'Iconic Amsterdam venue restored to the seed roster.',
    status: 'researching',
    tags: ['LIVE_MUSIC', 'EVENT_SPACE', 'EDM', 'TOURIST', 'LOCAL'],
    source: 'official website',
  }),
  v('melkweg-amsterdam', {
    name: 'Melkweg',
    category: 'Live Music Venue',
    city: 'Amsterdam',
    district: 'Centrum',
    website: 'https://www.melkweg.nl/en/',
    email: 'info@melkweg.nl', // verified on official visitor info page
    phone: '+31(0)20-5318181', // verified on official visitor info page
    has_djs: true,
    has_events: true,
    has_audio: true,
    outdoor: false,
    luxury_score: 3,
    tourist_area: true,
    music_type: 'Concerts, club nights, multidisciplinary',
    notes: 'Official visitor info page lists direct contact details.',
    status: 'researching',
    tags: ['LIVE_MUSIC', 'EVENT_SPACE', 'EDM', 'LOCAL', 'TOURIST'],
    source: 'official website',
  }),
  v('shelter-amsterdam', {
    name: 'Shelter Amsterdam',
    category: 'Nightclub',
    city: 'Amsterdam',
    district: 'Noord',
    website: 'https://www.shelteramsterdam.nl/',
    has_djs: true,
    has_events: true,
    has_audio: true,
    outdoor: false,
    luxury_score: 3,
    tourist_area: true,
    music_type: 'Techno, club nights',
    notes: 'Official site confirms event calendar and club contact channel.',
    status: 'researching',
    tags: ['NIGHTCLUB', 'TECHNO', 'LOCAL', 'TOURIST'],
    source: 'official website',
  }),
  v('club-nyx-amsterdam', {
    name: 'Club NYX',
    category: 'Nightclub',
    city: 'Amsterdam',
    district: 'Centrum',
    website: 'https://clubnyx.nl/',
    has_djs: true,
    has_events: true,
    has_audio: true,
    outdoor: false,
    luxury_score: 2,
    tourist_area: true,
    music_type: 'Pop, house, LGBTQ+ nightlife',
    notes: 'Official site confirms agenda, venue, and contact sections.',
    status: 'researching',
    tags: ['NIGHTCLUB', 'HOUSE', 'YOUTH', 'TOURIST', 'LOCAL'],
    source: 'official website',
  }),
  v('cabana-mare', {
    name: 'Cabana Mare Beach Club',
    category: 'Beach Club',
    city: 'Chania',
    district: 'Agia Marina',
    website: 'https://www.cabanamarechania.gr/',
    instagram: 'cabanamarebeachclub', // verified
    has_djs: true,
    has_events: true,
    has_audio: true,
    outdoor: true,
    luxury_score: 4,
    tourist_area: true,
    music_type: 'House, Open format',
    notes: 'VIP cabanas with jacuzzi, sushi bar, pool, themed parties with international DJs. Wedding capable.',
    status: 'ready',
    tags: ['BEACH_CLUB', 'SUNSET', 'LUXURY', 'TOURIST', 'OPEN_AIR', 'VIP', 'WEDDINGS', 'HOUSE', 'SEASONAL'],
    source: 'venue-outreach-DB.md brief',
  }),
  v('dna-night-club', {
    name: 'DNA Night Club',
    category: 'Nightclub',
    city: 'Chania',
    district: 'Old Venetian Harbour',
    instagram: 'dnaclubchania', // verified
    has_djs: true,
    has_events: true,
    has_audio: true,
    outdoor: false,
    luxury_score: 2,
    tourist_area: true,
    music_type: 'Open format, electronic',
    notes: 'Open every night 21:00-04:00. Old Venetian harbour location. Spacious dance floor, state-of-the-art sound + light.',
    status: 'ready',
    tags: ['NIGHTCLUB', 'TOURIST', 'AFTERHOURS', 'EDM'],
    source: 'venue-outreach-DB.md brief',
  }),
  v('klik-bar', {
    name: 'KLIK Bar',
    category: 'Bar with DJs',
    city: 'Chania',
    district: 'Old Venetian Port',
    instagram: 'klikbar_chania', // verified
    has_djs: true,
    has_events: true,
    has_audio: true,
    outdoor: false,
    luxury_score: 2,
    tourist_area: true,
    music_type: 'Dance, eclectic',
    notes: 'Dance bar behind old Mosque of the Janissaries. €10 entry incl. drink. Adults-only, gay-friendly. 90% tourists.',
    status: 'ready',
    tags: ['NIGHTCLUB', 'TOURIST', 'COCKTAIL', 'AFTERHOURS'],
    source: 'venue-outreach-DB.md brief',
  }),
  v('cameo-club', {
    name: 'Cameo Club',
    category: 'Nightclub',
    city: 'Hersonissos',
    district: 'Limenas Chersonisou',
    website: 'https://www.cameoclub.gr/',
    instagram: 'cameovibes', // verified
    email: 'info@cameoclub.gr', // verified on cameoclub.gr/contact
    phone: '+30 28970 25488', // verified
    has_djs: true,
    has_events: true,
    has_audio: true,
    outdoor: false,
    luxury_score: 3,
    tourist_area: true,
    music_type: 'House, R&B, dance',
    notes: 'Operating since 1993. Themed nights, fire dancers, percussion, capoeira, DJ programming.',
    status: 'ready',
    tags: ['NIGHTCLUB', 'TOURIST', 'HOUSE', 'AFTERHOURS', 'SEASONAL'],
    source: 'venue-outreach-DB.md brief',
  }),
  v('palm-beach-hersonissos', {
    name: 'Palm Beach Club Hersonissos',
    category: 'Beach Club',
    city: 'Hersonissos',
    website: 'https://www.palmbeachclub.gr/en',
    instagram: 'palmbeachclub', // verified
    email: 'info@palmbeachclub.gr', // verified on palmbeachclub.gr
    phone: '+30 6974 638305', // verified
    has_djs: true,
    has_events: true,
    has_audio: true,
    outdoor: true,
    luxury_score: 4,
    tourist_area: true,
    music_type: 'Open format, house',
    notes: 'Open since 2012. Day-to-night. Premium bars, VIP lounges, dance floor, sunset programming.',
    status: 'ready',
    tags: ['BEACH_CLUB', 'SUNSET', 'LUXURY', 'TOURIST', 'OPEN_AIR', 'VIP', 'HOUSE', 'SEASONAL'],
    source: 'venue-outreach-DB.md brief',
  }),
  v('club-sensation', {
    name: 'Club Sensation',
    category: 'Nightclub',
    city: 'Hersonissos',
    instagram: 'clubsensationofficial', // verified
    has_djs: true,
    has_events: true,
    has_audio: true,
    outdoor: false,
    luxury_score: 2,
    tourist_area: true,
    music_type: 'EDM, Dutch DJ talent',
    notes: 'Largest club in Chersonissos. Regular DJ nights, EDM-focused, Dutch artist programming.',
    status: 'ready',
    tags: ['NIGHTCLUB', 'TOURIST', 'EDM', 'YOUTH', 'AFTERHOURS', 'SEASONAL'],
    source: 'venue-outreach-DB.md brief',
  }),
  v('king-scorpio', {
    name: 'King Scorpio Beach Club Restaurant',
    category: 'Beach Restaurant',
    city: 'Hersonissos',
    website: 'https://scorpiobeachbar.com/',
    instagram: 'scorpiohersonissos', // verified
    has_djs: true,
    has_events: true,
    has_audio: true,
    outdoor: true,
    luxury_score: 4,
    tourist_area: true,
    music_type: 'Lounge, sunset',
    notes: 'Beach club restaurant between two bays. Sunbeds €30+. Mediterranean + Asian fusion. Sunset shows, signature cocktails.',
    status: 'ready',
    tags: ['BEACH_CLUB', 'RESTAURANT', 'SUNSET', 'LUXURY', 'TOURIST', 'OPEN_AIR', 'COCKTAIL', 'SEASONAL'],
    source: 'venue-outreach-DB.md brief',
  }),
  v('starbeach', {
    name: 'Starbeach',
    category: 'Beach Club',
    city: 'Hersonissos',
    website: 'https://www.starbeach.gr/',
    instagram: 'starbeach', // verified
    email: 'info@starbeach.gr', // verified
    phone: '+30 28970 502700', // verified
    has_djs: true,
    has_events: true,
    has_audio: true,
    outdoor: true,
    luxury_score: 3,
    tourist_area: true,
    music_type: 'EDM, pool party',
    notes: 'One of Europe’s biggest party destinations. Themed parties, pool parties. Strong international brand.',
    status: 'ready',
    tags: ['BEACH_CLUB', 'TOURIST', 'OPEN_AIR', 'EDM', 'YOUTH', 'SEASONAL', 'FESTIVAL'],
    source: 'venue-outreach-DB.md brief',
  }),
  v('minibar-rethymno', {
    name: 'Minibar',
    category: 'Bar with DJs',
    city: 'Rethymno',
    instagram: 'minibar_rethymno', // verified
    has_djs: true,
    has_events: true,
    has_audio: true,
    outdoor: false,
    luxury_score: 2,
    tourist_area: true,
    music_type: 'Eclectic, cocktail bar',
    notes: 'Cocktail-focused, mixed local/tourist crowd, late-night programming.',
    status: 'ready',
    tags: ['COCKTAIL', 'LOCAL', 'TOURIST', 'AFTERHOURS'],
    source: 'venue-outreach-DB.md brief',
  }),
  v('teatro-beach', {
    name: 'Teatro Beachside Bliss',
    category: 'Beach Restaurant',
    city: 'Ammoudara',
    district: 'Heraklion area',
    website: 'https://teatrobeach.gr/',
    has_djs: true,
    has_events: true,
    has_audio: true,
    outdoor: true,
    luxury_score: 4,
    tourist_area: true,
    music_type: 'Lounge, house',
    notes: 'Part of Enorme Hotels group. First-line Ammoudara beach. Resident DJs, Balinese beds, smooth lounge into evening sets.',
    status: 'ready',
    tags: ['BEACH_CLUB', 'RESTAURANT', 'SUNSET', 'LUXURY', 'TOURIST', 'OPEN_AIR', 'HOTEL', 'SEASONAL'],
    source: 'venue-outreach-DB.md brief',
  }),
  v('casa-dei-mezzo', {
    name: 'Casa dei Mezzo Chamber Music Festival',
    category: 'Festival',
    city: 'Makrigialos',
    district: 'Lasithi',
    website: 'https://www.casadeimezzo.com/',
    email: 'casachambermusic@gmail.com', // verified on casadeimezzo.com
    phone: '+30 28430 29183', // verified
    has_djs: false,
    has_events: true,
    has_audio: true,
    outdoor: false,
    luxury_score: 4,
    tourist_area: false,
    music_type: 'Classical chamber music',
    notes: 'Only annual classical chamber music festival on Crete. Started 2004. Six-day programme. Sunday Times: "most unique and intimate classical Summer festival in Europe."',
    status: 'researching',
    tags: ['FESTIVAL', 'CLASSICAL', 'CHAMBER_MUSIC', 'HIGH_END', 'SEASONAL', 'EVENT_SPACE'],
    source: 'venue-outreach-DB.md brief',
  }),
  // Named in brief but Instagram not publicly verifiable at build time. Left blank per "never fabricate".
  v('la-strada-rethymno', {
    name: 'La Strada',
    category: 'Bar with DJs',
    city: 'Rethymno',
    has_djs: true,
    has_events: true,
    has_audio: true,
    outdoor: false,
    luxury_score: 2,
    tourist_area: true,
    notes: 'Listed in brief. IG handle not publicly verified — needs research. Multiple "La Strada" venues across Crete (Agios Nikolaos, Hersonissos, Ierapetra); confirm Rethymno location before outreach.',
    status: 'researching',
    tags: ['LOCAL', 'TOURIST'],
    source: 'venue-outreach-DB.md brief',
  }),
  v('a-paradise-bar', {
    name: 'A Paradise Bar',
    category: 'Bar with DJs',
    city: 'Other',
    has_djs: true,
    has_events: true,
    has_audio: true,
    outdoor: true,
    luxury_score: 2,
    tourist_area: true,
    notes: 'Listed in brief. Location and IG not publicly verified — needs research.',
    status: 'researching',
    tags: ['COCKTAIL', 'TOURIST'],
    source: 'venue-outreach-DB.md brief',
  }),
  v('apollo-party-crete', {
    name: 'Apollo Party Crete',
    category: 'Event Organizer',
    city: 'Other',
    has_djs: true,
    has_events: true,
    has_audio: false,
    outdoor: true,
    luxury_score: 2,
    tourist_area: true,
    notes: 'Listed in brief as festival/event organizer. IG and contact not publicly verified — needs research.',
    status: 'researching',
    tags: ['FESTIVAL', 'EVENT_SPACE', 'SEASONAL'],
    source: 'venue-outreach-DB.md brief',
  }),
  v('fortuna-eternal-sun', {
    name: 'Fortuna Club (Eternal Sun Festival)',
    category: 'Festival',
    city: 'Other',
    has_djs: true,
    has_events: true,
    has_audio: true,
    outdoor: true,
    luxury_score: 3,
    tourist_area: true,
    notes: 'Listed in brief in context of Eternal Sun Festival. Location and contact not publicly verified — needs research.',
    status: 'researching',
    tags: ['FESTIVAL', 'EVENT_SPACE', 'OPEN_AIR', 'SEASONAL'],
    source: 'venue-outreach-DB.md brief',
  }),
]

export const SEED_VERSION = 2
